[workspace]
members = ["prisma-cli"]

[package]
name = "refeed-backend"
version = "0.1.0"
edition = "2021"


[dependencies]
reqwest = { version = "0.12.20", default-features = false, features = ["rustls-tls", "json"] }
feed-rs = "2.3.1"
futures = "0.3.31"
prisma-client-rust = { default-features = false, features = ["postgresql"], git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.11" }
serde = { version = "1.0.219", features = ["derive"] }
tokio = {features = ["macros","rt-multi-thread", "full"], version = "1.45.1"}
url = "2.5.4"
scraper = "0.23.1"
log = "0.4.27"
dotenv = "0.15.0"
image = "0.25.6"
rust-s3 = { version = "0.35.1", default-features = false, features = ["tokio-rustls-tls", "fail-on-err", "tags"] }
axum = "0.8.4"
tracing-subscriber = "0.3.19"
tower-http = {version = "0.6.6", features = ["cors"]}
blake3 = "1.8.2"
chrono = "0.4.41"
thiserror = "2.0.12"
fast_image_resize = "5.1.4"
nanoid="0.4.0"